version: '3'
services:
  angular-starter:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: angular-starter
    networks:
      - angular-starter
    ports:
      - '3000:3000'
    environment:
     - HOST=0.0.0.0
    command: npm run start
networks:
  angular-starter:
    driver: bridge
